/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String longInputMessage = "hello, my name is ";
        String inputMessage = "hello";
        Mobile mobile = new Mobile("name", "blue", "HUAWEI", 10);
        IPhone iPhone = new IPhone("name", "blue", "HUAWEI", 10);
        Andriod andriodMobile = new Andriod();
        mobile.makeACall(longInputMessage);
        mobile.printBasicInfo();
        iPhone.makeACall(longInputMessage);
        andriodMobile.makeACall(inputMessage);
        System.out.println(new App().getGreeting());
    }
}
