/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String inputMessage = "hello";
        Mobile mobile = new Mobile();
        IPhone iPhone = new IPhone();
        Andriod andriodMobile = new Andriod();
        mobile.makeACall(inputMessage);
        iPhone.makeACall(inputMessage);
        andriodMobile.makeACall(inputMessage);
        System.out.println(new App().getGreeting());
    }
}
